backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'test','mypage'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->redirect(['/user/admin/index']);


       // return $this->render('index');

        //  Тут нужно сделать редирект на екшн  actionIndex()

        // Который лежит по юрлу /var/www/html/vendor/dektrium/yii2-user/controllers/AdminController.php


    }

    public function actionTest()
    {
        Yii::$app->session->setFlash('success', 'Редирект с site/test');
        //редирект в контроллер дектрума
        //user - название компоненты (или модуля)
        //admin/index - контроллер и экшен
        //return $this->redirect(['/user/admin/index']);

        //редирект внутри контроллера на другой экшен
        return $this->redirect(['test-two']);

    }

    public function actionTestTwo()
    {
        var_dump('test');
    }




    public function actionMypage()
    {

        return $this->render('mypage');




    }






    public function actionHello()
    {

       echo 'Hello';




    }









    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Goods;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }




    //далее для страницы пробного магазина

    public function actionShop()
    {



        $shopbd2=Goods::find()->all();


        $id='shop';




      //  return $this->render('shop', ['shopbd2' => $shopbd2, 'id' => $id, 'modx' => $modx]);

       return $this->render('shop',compact('shopbd2','id')); // тут тлько для двух перемнных передача


    }




//    public function actionGoods()
//    {
//
//
//        $gid=$_POST['gid'];
//
//        $shopbd2=$_POST['curntshop'];
//
//        $id=$_POST['retid'];
//
//        $modx=Goods::find()->asArray()->where(['=','category_id',$gid])->all();
//
//
//
//
//
//
//         return $this->render('shop', [ 'shopbd2'=>$shopbd2,'modx' => $modx,'gid'=>$gid,'id'=>$id]);
//
//
//    }
//
//






























    public function actionTvset()
    {

   //  Показать товары из категории Телевизоры



        $shopbd2=Goods::find()->asArray()->where(['=','category_id','0'])->all();

//        $idbutton=$_GET['id'];

        $id='tvset';


        return $this->render('shop',compact('shopbd2','id'));
    }




    public function actionNotes()
    {

        //  Показать товары из категории Ноутбуки



        $shopbd2=Goods::find()->asArray()->where(['=','category_id','2'])->all();

        $id='notes';


        return $this->render('shop',compact('shopbd2','id'));
    }



    public function actionFreeze()
    {

        //  Показать товары из категории Холодильники



        $shopbd2=Goods::find()->asArray()->where(['=','category_id','1'])->all();


        $id='freeze';

        return $this->render('shop',compact('shopbd2','id'));
    }
































          //;;;;;;;;;;;;  ДАЛЕЕ СОРТИРОВКА ТОВАРОВ ;;;;;;;;;;;;;


    //;;;;;;;;;;;;  ДАЛЕЕ СОРТИРОВКА ТОВАРОВ ;;;;;;;;;;;;;


//    СОРТИРОВКА ПО ЦЕНЕ
    public function actionSortbycheapshop()
    {

        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему



        $shopbd2=Goods::find()->addOrderBy(['price' => SORT_ASC])->all();

        $id='shop';



        return $this->render('shop',compact('shopbd2','id'));


    }

    //    СОРТИРОВКА ПО АЛФАВИТУ
    public function actionSortbyabcshop()
    {
        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему


        $shopbd2=Goods::find()->asArray()->addOrderBy(['name' => SORT_ASC])->all();

        $id='shop';



        return $this->render('shop',compact('shopbd2','id'));


    }






    public function actionSortbynewshop()
    {




        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему


        $shopbd2=Goods::find()->addOrderBy(['date' =>SORT_DESC])->all();

        $id='shop';



        return $this->render('shop',compact('shopbd2','id'));


    }











//    ;;;;;;;;;;; СОРТИРОВКА ТЕЛЕВИЗОРОВ ;;;;;;;;;;;;;;;;;


   // ASC сортирует от меньшего к большему, а DESC от большего к меньшему.


//    СОРТИРОВКА ПО ЦЕНЕ
   public function actionSortbycheaptvset()
    {

        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.DESC от большего к меньшему.



        $shopbd2=Goods::find()->asArray()->where(['=','category_id','0'])->addOrderBy(['price' => SORT_ASC])->all();

        $id='tvset';



        return $this->render('shop',compact('shopbd2','id'));


    }

    //    СОРТИРОВКА ПО АЛФАВИТУ
    public function actionSortbyabctvset()
    {
        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему


        $shopbd2=Goods::find()->asArray()->where(['=','category_id','0'])->addOrderBy(['name' => SORT_ASC])->all();

        $id='tvset';



        return $this->render('shop',compact('shopbd2','id'));


    }






    public function actionSortbynewtvset()
    {



         // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему


        $shopbd2=Goods::find()->asArray()->where(['=','category_id','0'])->addOrderBy(['date' =>SORT_DESC])->all();

        $id='tvset';



        return $this->render('shop',compact('shopbd2','id'));


    }










//    ;;;;;;;;;  СОРТИРОВКА ХОЛОДИЛЬНИКОВ;;;;;;;;;;;


//    СОРТИРОВКА ПО ЦЕНЕ

    public function actionSortbycheapfreeze()
    {



        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему


        $shopbd2=Goods::find()->asArray()->where(['=','category_id','1'])->addOrderBy(['price' => SORT_ASC])->all();

        $id='freeze';



        return $this->render('shop',compact('shopbd2','id'));


    }




   //    СОРТИРОВКА ПО АЛФАВИТУ


    public function actionSortbyabcfreeze()
    {




        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему



        $shopbd2=Goods::find()->asArray()->where(['=','category_id','1'])->addOrderBy(['name' => SORT_ASC])->all();

        $id='freeze';



        return $this->render('shop',compact('shopbd2','id'));


    }






    public function actionSortbynewfreeze()
    {



        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему

        $shopbd2=Goods::find()->asArray()->where(['=','category_id','1'])->addOrderBy(['date' =>SORT_DESC])->all();

        $id='freeze';



        return $this->render('shop',compact('shopbd2','id'));


    }







//      ;;;;;;;;;;;;;;;     СОРТИРОВКА НОУТБУКОВ;;;;;;;;;;;;;;;;;;;;



    public function actionSortbyabcnote()
    {




        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему

        $shopbd2=Goods::find()->asArray()->where(['=','category_id','2'])->addOrderBy(['name' => SORT_ASC])->all();

        $id='notes';



        return $this->render('shop',compact('shopbd2','id'));


    }



// СОРТИРОВКА ПО ЦЕНЕ
    public function actionSortbycheapnotes()
    {
        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.от меньшего к большему
        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.от большего к меньшему

        $shopbd2=Goods::find()->asArray()->where(['=','category_id','2'])->addOrderBy(['price' => SORT_ASC])->all();

        $id='notes';



        return $this->render('shop',compact('shopbd2','id'));


    }







// СОРТИРОВКА -- НОВЫЕ
    public function actionSortbynewnotes()
    {

        // SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.


        // SORT_DESC используется с array_multisort() для сортировки в порядке убывания.

        $shopbd2=Goods::find()->asArray()->where(['=','category_id','2'])->addOrderBy(['date' =>SORT_DESC ])->all();

        $id='notes';



        return $this->render('shop',compact('shopbd2','id'));


    }









































































    public function actionTest()
    {


// SORT_ASC используется с array_multisort() для сортировки в порядке возрастания.

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/included.php
<?php
/**
 * Created by PhpStorm.
 * User: oleg
 * Date: 19.02.18
 * Time: 20:12
 */


?>


        <!--  МОДАЛЬНОЕ ОКНО-->


        <div id="<?php echo $current['id']; ?>" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
                        <h4 class="modal-title"><?php echo 'Купить'.$current['name'];  ?></h4>
</div>
<div class="modal-body">
    <ul>
        <li>Цена: <?php  echo $current['price']; ?>  </li>
        <li>Дата поставки:<?php   echo $current['date']; ?> </li>

    </ul>


</div>
<div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button></div>
</div>
</div>
</div>


<!--       КОНЕЦ   МОДАЛЬНОГО ОКНА-->

frontend/views/site/shop.php
<?php
/**
 * Created by PhpStorm.
 * User: oleg
 * Date: 06.02.18
 * Time: 19:03
 */


use yii\widgets\Pjax;
use yii\helpers\Html; // Для создания кнопки

$this->title = 'Cтраница магазина';


?>



<h1>Cтраница магазина</h1>


<?php


//foreach ($shopbd as $current) {
//    echo $current['name'];
//    echo $current['price'];
//    echo $current['date'];
//
//}

?>



<?php Pjax::begin(); ?>







<div id="sidebar-left" class="col-sm-2 sidebar left_content">
  <h5> <i>Категории товаров </i></h5>



    <?= Html::beginForm(['site/tvset'], 'get', ['data-pjax' => '', 'class' => '']); ?>

    <?= Html::a('Телевизоры', ['site/tvset'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\tvset' ] ],'class'=>'c_names' ])?>

    <?= Html::endForm() ?>


    <?= Html::beginForm(['site/freeze'], 'get', ['data-pjax' => '', 'class' => '']); ?>
       <?= Html::a('Холодильники', ['site/freeze'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\freeze' ] ],'class'=>'c_names' ])?>

    <?= Html::endForm() ?>


    <?= Html::beginForm(['site/notes'], 'get', ['data-pjax' => '', 'class' => '']); ?>

    <?= Html::a('Ноутбуки', ['site/notes'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\notes' ] ],'class'=>'c_names' ])?>

    <?= Html::endForm() ?>




    <?= Html::beginForm(['site/shop'], 'post', ['data-pjax' => '', 'class' => '']); ?>

    <?= Html::a('ВСЕ ТОВАРЫ', ['site/shop'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\shop' ] ],'class'=>'c_names' ])?>

    <?= Html::endForm() ?>













</div>





<!--      СОРТИРОВКА    -->








<div class="dropdown drodowngoods">
    <a class="dropdown-toggle" type="button" data-toggle="dropdown">Сортировка товаров</a>
    <ul class="dropdown-menu">






        <!--  ;;;;;;; ОБЩАЯ  СОРТИРОВКА  ;;;;;;;;;;;;; -->

        <!--    CОРТИРОВКА ПО ЦЕНЕ  -->




        <?php if($id=='shop'):   ?>

            <?= Html::beginForm(['site/sortbycheapshop'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Дешевые', ['site/sortbycheapshop'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbycheapshop' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

        <!--    CОРТИРОВКА ПО АЛФАВИТУ (ОТ А ДО Я)-->


        <?php if($id=='shop'):   ?>

            <?= Html::beginForm(['site/sortbyabcshop'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('По алфавиту (А-Z)', ['site/sortbyabcshop'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbyabcshop' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

        <!--    CОРТИРОВКА / НОВЫЕ /  -->


        <?php if($id=='shop'):   ?>

            <?= Html::beginForm(['site/sortbynewshop'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Новые', ['site/sortbynewshop'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbynewshop' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>
































        <!--  ;;;;;;;СОРТИРОВКА ДЛЯ ТЕЛЕВИЗОРОВ  ;;;;;;;;;;;;; -->

        <!--    CОРТИРОВКА ПО ЦЕНЕ  -->


        <?php if($id=='tvset'):   ?>

            <?= Html::beginForm(['site/sortbycheaptvset'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Дешевые', ['site/sortbycheaptvset'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbycheaptvset' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

        <!--    CОРТИРОВКА ПО АЛФАВИТУ (ОТ А ДО Я)-->


        <?php if($id=='tvset'):   ?>

            <?= Html::beginForm(['site/sortbyabctvset'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('По алфавиту (А-Z)', ['site/sortbyabctvset'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbyabctvset' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

        <!--    CОРТИРОВКА / НОВЫЕ /  -->


        <?php if($id=='tvset'):   ?>

            <?= Html::beginForm(['site/sortbynewtvset'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Новые', ['site/sortbynewtvset'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbynewtvset' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

















        <!--  ;;;;;;;СОРТИРОВКА ДЛЯ ХОЛОДИЛЬНИКОВ ;;;;;;;;;;;;; -->

        <!--    CОРТИРОВКА ПО ЦЕНЕ  -->


        <?php if($id=='freeze'):   ?>

            <?= Html::beginForm(['site/sortbycheapfreeze'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Дешевые', ['site/sortbycheapfreeze'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbycheapfreeze' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

        <!--    CОРТИРОВКА ПО АЛФАВИТУ (ОТ А ДО Я)-->


        <?php if($id=='freeze'):   ?>

            <?= Html::beginForm(['site/sortbyabcfreeze'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('По алфавиту (А-Z)', ['site/sortbyabcfreeze'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbyabcfreeze' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>

       <!--    CОРТИРОВКА / НОВЫЕ /  -->


        <?php if($id=='freeze'):   ?>

            <?= Html::beginForm(['site/sortbynewfreeze'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Новые', ['site/sortbynewfreeze'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbynewfreeze' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>















          <!-- ;;;;; СОРТИРОВКА ДЛЯ НОУТБУКОВ;;;;;;;;-->

        <!--    CОРТИРОВКА ПО ЦЕНЕ--дешевка-->


        <?php if($id=='notes'):   ?>

            <?= Html::beginForm(['site/sortbycheapnotes'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Дешевые', ['site/sortbycheapnotes'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbycheapnotes' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>


        <!--    CОРТИРОВКА ПО АЛФАВИТУ (ОТ А ДО Я)-->


        <?php if($id=='notes'):   ?>

        <?= Html::beginForm(['site/sortbyabcnote'], 'post', ['data-pjax' => '', 'class' => '']); ?>

        <li class="droplist"> <?= Html::a('По алфавиту (А-Z)', ['site/sortbyabcnote'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbyabcnote' ] ],'class'=>'droplist' ])?></li>

        <?= Html::endForm() ?>


        <?php endif;  ?>


        <!--    CОРТИРОВКА / НОВЫЕ /  -->


        <?php if($id=='notes'):   ?>

            <?= Html::beginForm(['site/sortbynewnotes'], 'post', ['data-pjax' => '', 'class' => '']); ?>

            <li class="droplist"> <?= Html::a('Новые', ['site/sortbynewnotes'], ['data' => ['method' => 'post','params' => [ 'action' => 'site\sortbynewnotes' ] ],'class'=>'droplist' ])?></li>

            <?= Html::endForm() ?>


        <?php endif;  ?>
















    </ul>
</div>




<!-- ;;;;;;;;;;;;;; КОНЕЦ СОРТИРОВКИ ;;;;;;;;;;;;;;;;;;;;;;;;; ->






<?php

//var_dump($shopbd2);

//foreach ($shopbd2 as $current) {
//    echo $current['name'];
//    echo $current['price'];
//    echo $current['date'];
//
//}
//


?>



























<!--   ;;;;;;;;;;;;;;  ТОВАРЫ    ;;;;;;;;;;;;;      -->




<div id="goodslist" class="row row_catalog_products ">



    <?php




//    var_dump($shopbd2);
//
//    echo 'End of ends';
//
//    die();

    ?>


    <?php foreach ($shopbd2  as $current): ?>





        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6 col_product">


            <div class="product">

                <div class="wrapper_product_hover">
                    <div class="product_hover">
                        <div class="p_description">

                            <p><?php   echo $current['name'];   ?></p>


                            <div class="new_old_price clearfix">
                                <p class="price"><span class="new_price"><span class="ccp">Цена </span><?php  echo $current['price']; ?> </span></p>

                     <button  class="btn btn-primary btnmain" type="submit" data-toggle="modal" data-target="<?= '#'.$current['id'];?>" >Купить</button>




                            </div>

                            <table class="listing_attrs"><tbody><tr><td>Дата поставки:<?php   echo $current['date']; ?></td></tr></tbody></table>

                        </div>
                    </div>
                </div>
            </div>




        </div>



        <!--  МОДАЛЬНОЕ ОКНО-->


        <div id="" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
                        <h4 class="modal-title"><?php echo 'Купить'.$current['name'];  ?></h4>
                    </div>
                    <div class="modal-body">
                        <ul>
                            <li>Цена: <?php  echo $current['price']; ?>  </li>
                            <li>Дата поставки:<?php   echo $current['date']; ?> </li>

                        </ul>


                    </div>
                    <div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button></div>
                </div>
            </div>
        </div>


        <!--       КОНЕЦ   МОДАЛЬНОГО ОКНА-->









    <?php endforeach; ?>





    <?php



//    foreach ($modx as $current) {
//        echo $current['name'];
//        echo $current['price'];
//        echo $current['date'];
//
//    }
//


    ?>


















</div>






<?php


// echo 'Айдибатон'.$id;





?>




<?php Pjax::end(); ?>


<button class="btnmain">fff</button>

<script>


    var btn=parentDOM.getElementsByClassName('btnmain');


    btn.onclick=function(){


        alert("Hello user 555 !!");

    };




</script>